#!/usr/bin/env bash
#
# Call yarn shadow-cljs watch and then launch node fonda.js.
#
# Note: the $@ parameters are forwarded to yarn shadow-cljs not to the node
# command.
#
set -euo pipefail

output_dir=dist
output_file=$output_dir/fonda.js

shadow_dir=.shadow-cljs
shadow_pid_file=$shadow_dir/server.pid

shadow_build="lib"
shadow_bin="yarn shadow-cljs"
shadow_subcmd="watch"

node_bin=$(which node)
node_opts="--inspect $output_file"

function do_cleanup {
  pkill $(cat "$shadow_pid_file");
}

set +e
rm -v "$output_file"
set -e

shadow_cmd="$shadow_bin $shadow_subcmd $shadow_build $@"
echo "Executing \"$shadow_cmd\"..."
$shadow_cmd &

# active loop waiting for the js file to appear
i=1
spinner="/-\|"
echo -n ' '
while [ ! -f "$output_file" ]; do
    for c in / - \\ \|; do
        printf '\b%s' "$c";
        sleep .1
    done
done

node_cmd="$node_bin $node_opts"
echo "The shadow-cljs REPL is up."
echo "Executing \"$node_cmd\"..."

$node_cmd

trap "set +e; do_cleanup" ERR SIGTERM SIGINT EXIT
